######################### theme kunka condigure ##############################################
# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: Jekyll Theme
description: Just another Jekyll theme design and code by zhanxin.info.
keywords: Jekyll Theme
url: /Blog
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: index.html
  - text: 分类目录 
    url: navigations/categories.html
  - text: 文章归档
    url: navigations/archives.html
  - text: 联系我
    url: navigations/contact.html
  - text: 友情链接
    url: navigations/links.html

#Author config
author:
    name: 嗡汤圆
    email: 18600647615@163.com
    imageLink: https://wengshengyuan.github.io/Blog/images/Avatar-big.jpg
    simpleIntro: 我是 嗡汤圆 
    detailIntro:
            <p>这个博客是参考 minixalpha的博客为模板填充如自己的日志生成的。</p>
            <p>有很长一段时间我仅仅是使用为知笔记或者有道笔记来记录我的学习笔记，有的原创，也有摘录。很久以前我就想自己建立一个博客，但是苦于没有合适的地方，一些常规的博客网站不能随心所欲得定制样式，最终还是Github比较理想，而且还能顺带托管我的一些代码。虽然这些代码很low，但是总能养成一个良好的维护习惯，不至于辛辛苦苦写的一些代码最终被一不小心删除。</p>
            <p>最后感谢minixalpha能提供如此方便快捷的博客框架。</p>
            <h3>由于百度无法爬到Git，因此转账CSDN，请移步:http://blog.csdn.net/tzdwsy  ^.^</h3>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
#  - class: icon-weibo
#    url: http://weibo.com/wengshengyuan
  - class: icon-github-alt
    url: http://github.com/wengshengyuan
  - class: icon-envelope
    url: mailto:18600647615@163.com

#Links
customLinks:
  - item:
    - text: czxttkl
      url: http://129.10.79.19/wordpress/
    message: Friends
  - item:
    - text: 掌心
      url: http://www.zhanxin.info
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://www.zhanxin.info/themes.html
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#comment config
disqus:
  config: false
  id: wengshengyuan




#################################### global configure #######################################
username: wengshengyuan
baseurl: /Blog
markdown: redcarpet
safe: false
highlighter: pygments
title: 嗡汤圆
description: 由于百度无法爬到Git，因此转账CSDN，请移步:http://blog.csdn.net/tzdwsy  ^.^
theme: hack
disqusname: wengshengyuan



# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine, kunka
# those themes are all come from GitHub Pages Themes
